### ISSUE TITLE
Footer - Follow us bar - X (ex-Twitter) / social button

### ISSUE THREAD

**Issue by MathieuPomm** [Orange-OpenSource/Orange-Boosted-Bootstrap#2643] opened 2024-07-23 18:41 UTC
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello, I'm searching the new icon for X (ex-Twitter) to be able to use it as a social button in the follow bar in the footer.
Could it be possible to add it in the social buttons in Boosted ? (and replace maybe the existing previous icon with the bird ?).

### Motivation and context

This is a request from several countries to be able to have the new icon in follow bar.
Some countries have already make some changes by themselves, but we think we need to homogeneize the behavior...

**Comment by julien-deramond** [comment] 2024-07-24 04:33
Thanks for reporting this feature request @MathieuPomm 
It's actually a duplicate of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2182
I'm going to close yours to have a unique reference. Please subscribe to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2182, we'll update it with the latest news and start the implementation ASAP, hopefully for the v5.3.4 if the design specs are available at that time.

**Closed by julien-deramond** 2024-07-24 04:33 UTC
Labels: feature

**Comment by julien-deramond** [comment] 2024-07-26 05:53
FYI @MathieuPomm, https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2644 has been merged. The X social button will be in the next v5.3.4 release.

**Comment by MathieuPomm** [comment] 2024-07-26 07:30
Thanks @julien-deramond for your feedback !
