### ISSUE TITLE
No border color in firefox select field when he focused

### ISSUE THREAD

**Issue by SimonF30** [Orange-OpenSource/Orange-Boosted-Bootstrap#979] opened 2021-12-14 10:20 UTC
### Prerequisites

- [X] I have [searched](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In firefox the focus on the select fields are not visible.

You have the example here https://boosted.orange.com/docs/5.0/forms/select/

While examining the code I noticed that we had this which disables the focus in the file scss/forms/_form-select.scss

  ```
// Remove outline from select box in FF
     &: - moz-focusring {
       color: transparent;
       text-shadow: 0 0 0 $ form-select-color;
     } 
```
maybe removing it will solve the problem 

Thank you for your Help

### Reduced test cases

https://boosted.orange.com/docs/5.0/forms/select/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Boosted are you using?

v5.1.3

**Comment by julien-deramond** [comment] 2021-12-14 10:31
Thanks for your report @SimonF30. It is a duplicate of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/715. You'll have a fix in the next Boosted 5.2.0 version :)

**Closed by julien-deramond** 2021-12-14 10:31 UTC
Labels: bug
